#!/bin/sh -l

#$ -l mem_total=256G
#$ -pe omp 16

echo "Executing FEF_VM_wFS_argJ.py '$1'."

module load miniconda/4.9.2

conda activate brienv

cd /projectnb/crc-nak/brpp/Full_model_04_06/

python FEF_VM_wFS_argJ.py $1
