#!/bin/sh -l

#$ -l mem_total=256G
#$ -pe omp 16
#$ -t 1-11

SIinputs=(-10 -7 -4 -1 2 5 8 11 14 17 20)
index=$(($SGE_TASK_ID-1))
SIinput=${SIinputs[$index]}

echo "Executing FEF_and_LIP_argJgg.py "$SIinput" for gFS from 1 to 4 and gVS from 1 to 0.1."

module load miniconda/4.9.2

conda activate brienv

cd /projectnb/crc-nak/brpp/Full_model_04_06/

for i in 1 0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1;
do
for j in 1 1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4;
do
python FEF_and_LIP_argJgg.py $SIinput $j $i;
done;
done
