#!/bin/sh -l

#$ -l mem_total=256G
#$ -pe omp 16

echo "Executing FEF_and_LIP_argJgg.py '$1' '$2' '$3'."

module load miniconda/4.9.2

conda activate brienv

cd /projectnb/crc-nak/brpp/Full_model_04_06/

python FEF_and_LIP_argJgg.py $1 $2 $3
